name: woké
favicon: null
layout_spectrum: 0.36915
typography_spectrum: 0.13557
title: 'Woké: You create, We wok'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eee74d'
    - '#fffffe'
    - '#545554'
    - '#85bf41'
    - '#8f8f62'
  brandStrength: 0.8125
  lightness: 0.9995235695969313
  saturation: 0.3037204269785434
  rhythmicContrast: 0.988655858905986
purpose: []
